---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freshrss
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: rook-ceph
      namespace: rook-ceph

  values:
    image:
      repository: ghcr.io/linuxserver/freshrss
      tag: 1.20.1
      pullPolicy: IfNotPresent

    env:
      TZ: "${TZ}"

    service:
      main:
        ports:
          http:
            port: 80

    persistence:
      config:
        enabled: true
        existingClaim: freshrss-config-v1

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: &host "freshrss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        cpu: 15m
        memory: 64M