---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m

  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: rook-ceph
      namespace: rook-ceph

  values:
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: "1.1.4"

    env:
      TZ: "${TZ}"

    service:
      main:
        ports:
          http:
            port: 6767

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "subtitles"
        hosts:
          - host: &host "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: bazarr-tls

    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER}"
            path: /mnt/user/media
        mountPath: /media
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER}"
            path: /mnt/user/k3s-backup/bazarr
        mountPath: /config/Backups
        readOnly: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      supplementalGroups:
        - 100

    resources:
      requests:
        cpu: 15m
        memory: 204M
      limits:
        cpu: 15m
        memory: 204M
