---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: minio
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2022-11-29T23-40-49Z
    mode: standalone
    ignoreChartChecksums: true
    rootUser: "${SECRET_MINIO_ROOT_USER}"
    rootPassword: "${SECRET_MINIO_ROOT_PASSWORD}"
    drivesPerNode: 1
    replicas: 1
    persistence:
      enabled: true
      existingClaim: minio-data-v1
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN}"
        external-dns.home.arpa/enabled: "true"
      path: /
      hosts:
        - &host-api "s3.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host-api
  
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      path: /
      hosts:
        - &host-console "minio.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host-console
    users: []
    environment:
      TZ: "${TZ}"
      MINIO_UPDATE: "off"
      MINIO_PROMETHEUS_JOB_ID: "minio"
      MINIO_PROMETHEUS_URL: "http://thanos-query.monitoring:9090"
      MINIO_SERVER_URL: "https://s3.${SECRET_DOMAIN}"
    metrics:
      serviceMonitor:
        enabled: true
        public: true

    resources:
      requests:
        cpu: 23m
        memory: 477M
      limits:
        cpu: 23m
        memory: 477M