---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: rook-ceph
      namespace: rook-ceph

  values:
    image:
      repository: jellyfin/jellyfin
      tag: "10.8.8"

    env:
      TZ: "${TZ}"
      JELLYFIN_CACHE_DIR: /config/cache

    service:
      main:
        ports:
          http:
            port: 8096

    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 568

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-open-play"
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: jellyfin-tls

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-data-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER}"
            path: /mnt/user/media
        mountPath: /media
      transcode:
        enabled: true
        type: emptyDir

    resources:
      requests:
        cpu: 15m
        memory: 1739M
      limits:
        cpu: 15m
        memory: 1739M
