---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-tools
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system

  install:
    createNamespace: true
    crds: CreateReplace

  upgrade:
    crds: CreateReplace

  values:
    nodeFeatureRule:
      createCRD: true

    master:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "node-role.kubernetes.io/master"
                    operator: In
                    values: [""]

      resources:
        requests:
          cpu: 23m
          memory: 64M
        limits:
          cpu: 23m
          memory: 64M

    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf
      config:
        core:
          sources:
            - custom
            - pci
            - usb

        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"
          custom:
            - name: "intel-gpu"
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]
            - name: "ups-apc"
              matchOn:
                - usbId:
                    class: ["03"]
                    vendor: ["051d"]
                    device: ["0002"]
            - name: "zwave"
              matchOn:
                - usbId:
                    vendor: ["0658"]
                    device: ["0200"]
            - name: "ender3"
              matchOn:
                - usbId:
                    vendor: ["1eaf"]
                    device: ["0004"]
            - name: "zigbee"
              matchOn:
                - usbId:
                    vendor: ["1a86"]
                    device: ["55d4"]

      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 15m
          memory: 64M

      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
