---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app goldilocks
  namespace: monitoring
spec:
  interval: 60m
  chart:
    spec:
      chart: *app
      version: 6.3.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 60m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  # Values link: https://github.com/FairwindsOps/charts/blob/master/stable/goldilocks/values.yaml
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 145M
        limits:
          memory: 174M

    dashboard:
      replicaCount: 1

      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix

        tls:
          - hosts:
              - "goldilocks.${SECRET_DOMAIN}"

      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 256M