---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: rook-ceph
      namespace: rook-ceph

  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.9.5

    env:
      TZ: "${TZ}"

    hostNetwork: true

    dnsPolicy: ClusterFirstWithHostNet

    envFrom:
      - secretRef:
          name: home-assistant-secrets

    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${LB_HOMEASSISTANT}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podAnnotations:
      secret.reloader.stakater.com/reload: home-assistant-secrets

    resources:
      requests:
        cpu: 35m
        memory: 324M

    addons:
      codeserver:
        enabled: true

        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.6.0

        workingDir: "/config"

        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            hajimari.io/enable: "true"
            hajimari.io/icon: "microsoft-visual-studio-code"
          hosts:
            - host: &host "ha-vscode.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host

        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"

        volumeMounts:
          - name: config
            mountPath: /config

        resources:
          requests:
            cpu: 11m
            memory: 94M