---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-influxdb-v1
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block