---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jellyseerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  values:
    image:
      repository: docker.io/fallenbagel/jellyseerr
      tag: 1.3.0

    env:
      TZ: "${TZ}"
      LOG_LEVEL: "info"
      PORT: &port 80

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-search"
        hosts:
          - host: &host "jellyseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: jellyseerr-tls

    persistence:
      config:
        enabled: true
        existingClaim: jellyseerr-config-v1
        mountPath: /app/config

    resources:
      requests:
        cpu: 15m
        memory: 352M
      limits:
        cpu: 15m
        memory: 352M