---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghostfolio
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    createNamespace: true
  values:
    image:
      repository: ghostfolio/ghostfolio
      tag: "1.212.0"
    env:
      TZ: "${TZ}"
      ACCESS_TOKEN_SALT: "${SECRET_GHOSTFOLIO_ACCESS_TOKEN_SALT}"
      BASE_CURRENCY: "EUR"
      DATABASE_URL: "postgresql://${SECRET_GHOSTFOLIO_POSTGRES_USER}:${SECRET_GHOSTFOLIO_POSTGRES_PASSWORD}@${SECRET_GHOSTFOLIO_POSTGRES_HOST}:5432/${SECRET_GHOSTFOLIO_POSTGRES_DATABASE}?sslmode=prefer"
      JWT_SECRET_KEY: "${SECRET_GHOSTFOLIO_JWT_SECRET_KEY}"
      REDIS_HOST: "localhost"
      REDIS_PORT: "6379"
      NODE_ENV: "production"

    service:
      main:
        ports:
          http:
            port: 3333

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "bank"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host ghostfolio.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        memory: 300Mi

    additionalContainers:
      - name: broker
        image: redis:7.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 11m
            memory: 32M
          limits:
            memory: 32M