---
- name: Create backup-paperless directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ containers_base_dir }}/apps/rclone/backup-paperless"

- name: Create backup-paperless docker compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ containers_base_dir }}/apps/rclone/backup-paperless/docker-compose.yml"
    mode: 0755
  vars:
    container_name: backup-paperless
    source: /shares/dms-export
    destination: b2:teqqy-paperless-backup/

- name: Create backup-paperless systemd service file
  ansible.builtin.template:
    src: docker-compose@backup.service.j2
    dest: /etc/systemd/system/docker-compose@backup-paperless.service
    mode: 0644
#   vars:
#     heartbeat_url: "{{ SECRET_UPTIMEROBOT_HEARTBEAT_paperless_B2 }}"

- name: Create backup-paperless systemd timer file
  ansible.builtin.copy:
    src: files/docker-compose@backup.timer
    dest: /etc/systemd/system/docker-compose@backup-paperless.timer
    mode: 0644
  register: systemd

- name: Enable backup-paperless systemd timer unit
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - docker-compose@backup-paperless.timer
  when: systemd.changed
