#ENC[AES256_GCM,data:uxH0cobuloa/ykgrh1/CB3Q=,iv:Z6V6nLPeL3xvdWIFGqne5fv9ddltSdkCfG8FTJF3g6o=,tag:Hkr4fzgeherpD4P0g7CWoQ==,type:comment]
ansible_become_pass: ENC[AES256_GCM,data:0/kAtYM0,iv:3jJr3Wr2n9dr1H3r1PAcozFCEmpTjUM7ID5A5p64UuU=,tag:PLVOL29z4c0Mq0iGTm8orQ==,type:str]
k3s_become_for_all: ENC[AES256_GCM,data:1tpqcA==,iv:kNw+qqNTpAEitaq7QdUAtr/IM2HYWbBtAiDiVf++pnk=,tag:twb5fijX3BpGiBwVRMEZoA==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmnhp30e40u4q54znn8ysz3atvee5k4q9r585y8mzxz9xuuxm37spk5w4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMmVWTVU1dUNPdEw1QThO
            b2trc3dOQjFaYUw4Wi84b3pHYUFUSUM5NkhzClU1dS9TRmJqYkZtcC8wajZMM2lx
            Wjd6YzVxekhxNHpoTFNSU2l3Q0cxNW8KLS0tIHZVanNuTU1zZ1YxRHBTbjdhVksz
            dWhON3FwcEx1cS9nM1hYd3AwSjFNKzAKCHDMLshP+bsO5oWmAtNAGW+ExQkiMqdx
            MIJTCCjwo5YXHBV/63TlJV8jR6//C9ISeQ3/fP9ypZnkhnldhZPlqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-07T13:01:29Z"
    mac: ENC[AES256_GCM,data:XQdyIpSMGAJWaJ/llk+9R/8S67sNMjE9PNCqPdyExWVnFaJyh/zjyUwmh0QMYbWrpdAN1zxf4QeP43U8m2TZGTyA57bC98bG7vbskJEE4MdS+lHAA3hv1i2CIKIppDKRzeMXBsmhTWdmvQQZVNKC/++aSgCOwK44Q1S4VqSC0JM=,iv:olbnSaFFIkup+Sst+v1b0UWbhzLW6G9F25Q2SHa6PKI=,tag:nKH43q1w8HUCQRJGV4ZKFQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
