#ENC[AES256_GCM,data:KxTsjI2jA1yw4nraJx27EzQ=,iv:G+FFog3RJWA9wMBQI4CXnTAzNJ2NsTEnHGA7BElnr/Q=,tag:yr2S+mz8Ia3kyS1nHqR6ww==,type:comment]
ansible_become_pass: ENC[AES256_GCM,data:HpYVbco=,iv:esV8pc1A5KyqlJ1RKpeceFYD40RUGBcjP/SqxzO1OD0=,tag:5PYty3gjmGDvaiKDVRvtZQ==,type:str]
k3s_become_for_all: ENC[AES256_GCM,data:6xnxvA==,iv:nceyHBZb7DAlS+eGipkn96OEWluOJh5t+oQRs4xWm04=,tag:vsfmWYrCgLCTaDS2GLcBzg==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmnhp30e40u4q54znn8ysz3atvee5k4q9r585y8mzxz9xuuxm37spk5w4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZzNNS0Q5WWFZOVVXbEVL
            Q0ZheUNUTVhUdFZvK25qc0JJVlhiVlVXRjIwCldlZjV6dWIvLzVEZ0hodnJrZ0VB
            cFZTTXZBZ1l2amU0dUZ0aXVYdm12dncKLS0tIEJralVHVU9FUUV6WGF1bFpOVUZC
            MVA3cFBvL0krZ1o0WjhpMGwxbU43M1UKs8TCN7D6ipNQetRYDES2HaD8OceSrFtd
            whIN70q63XtAJOgJogJXU8toa+ob5tyTMjwozzVVVEF0ez+pb8g8qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T17:42:28Z"
    mac: ENC[AES256_GCM,data:Wr4suKzpE3lJjxrJwY8lNi0YMM+cAZGpW0L0APt2KNfu9X5x0ZtmH+Rf5/+Cpfedf6uywuhvCsWeNYKYBvuId+Nru+do/G3+DASIqdDzuGhK24XWm1rGrae348k6J/3YJWOKZpv7uotgPp4+Ik13yyvyu/DHMKfHhhYF1d97rok=,iv:Pi905KP/UnuBHw0GntKirqXsfgmiUjUhyG8lrisa2RU=,tag:Am0g+q3cmh9cHee2d/urEA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
