#ENC[AES256_GCM,data:KxTsjI2jA1yw4nraJx27EzQ=,iv:G+FFog3RJWA9wMBQI4CXnTAzNJ2NsTEnHGA7BElnr/Q=,tag:yr2S+mz8Ia3kyS1nHqR6ww==,type:comment]
ansible_become_pass: ENC[AES256_GCM,data:H6rL3vMB,iv:vcWGZNNrQtwM3Je5PqKVgSd+eR7upVfzXmOqQ8+VzBQ=,tag:aaLIhvslXNUAvF1cfWbyFw==,type:str]
k3s_become_for_all: ENC[AES256_GCM,data:6xnxvA==,iv:nceyHBZb7DAlS+eGipkn96OEWluOJh5t+oQRs4xWm04=,tag:vsfmWYrCgLCTaDS2GLcBzg==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmnhp30e40u4q54znn8ysz3atvee5k4q9r585y8mzxz9xuuxm37spk5w4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZzNNS0Q5WWFZOVVXbEVL
            Q0ZheUNUTVhUdFZvK25qc0JJVlhiVlVXRjIwCldlZjV6dWIvLzVEZ0hodnJrZ0VB
            cFZTTXZBZ1l2amU0dUZ0aXVYdm12dncKLS0tIEJralVHVU9FUUV6WGF1bFpOVUZC
            MVA3cFBvL0krZ1o0WjhpMGwxbU43M1UKs8TCN7D6ipNQetRYDES2HaD8OceSrFtd
            whIN70q63XtAJOgJogJXU8toa+ob5tyTMjwozzVVVEF0ez+pb8g8qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-07T13:01:34Z"
    mac: ENC[AES256_GCM,data:sY1OlsM63HD3H+RFg7SoMonbekjIJNA5Z5i/DB59q+rZ7YeWJc6PVjnOe43WerCxEz8i6pjzFGMge/rSbGaulY9zM4UD8RVJHW7UlPSevOV1n+mdlOcjD6utWvlljrfxWrut6XAyiOYdVHjtuoySu6l+7EwrAVplafvmesCz2ss=,iv:UFemR3CP1KrH8o37xuXkLPOtSkvElkX68SfgR2mn/1w=,tag:ibpewdcBSDNo9nQGzxKHhw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
