#ENC[AES256_GCM,data:LD59CMa82Ju6zN5+OA8+N0Q=,iv:/wWFLmj7cHHwnpkEsSn4CB5QgPvFqMINO6omnOKdrCo=,tag:iKV/qw/Fo1eYWjuv/EwWIw==,type:comment]
ansible_become_pass: ENC[AES256_GCM,data:qEculAU=,iv:tgH7xu/Gcrs1JzjgS/OZ/cw/RCrhWJTOcF9wMjlgsjU=,tag:yrVth0D0WQ7ChY1DIhRS5Q==,type:str]
k3s_become_for_all: ENC[AES256_GCM,data:wvSkTA==,iv:Do/tERpK9hcwIC4meXym48YE8GWJkkzJNtOqv9so/ng=,tag:7t8x0IUTHyZ2b/tc0OeFpQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmnhp30e40u4q54znn8ysz3atvee5k4q9r585y8mzxz9xuuxm37spk5w4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSVV1WXJkcTZQWGZGMC9B
            N1dnRjZRNkxoN3JLZEFSUEJyc0dreTFRWkVzCmVZeUlHaXpVV08veVNPTzg2NFN3
            bTIxTytIMEdRWU5GZjg5aGRLQXdrN0kKLS0tIFRyTjY4UUVObjVYK1JIVExOZC9P
            NVk1d21mYlB6Qi90dWhPMU54SUJjakEK9MJOotRFl0vBEN7rY/CCZNTo6RIySGV3
            N4Dtewsy/S8ZevOzlUrgw7Ei8qsppYo/b0C2hQuAOKu3iS4a68r4RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T17:42:24Z"
    mac: ENC[AES256_GCM,data:zVv+HuFjVUCpdXfjKl5wi0xq8L81kH4RCY8ky6iMz2IhuPousedhbUdgkv+15RvZF3b9IrzzgtQDP+9R1NcffakkLaB88dMKo5SxmdXn2xlS43wXsklU79Y/oAdkStPw2JF7NTa5RCvTK8olK871Kjt9Go15LsybsSK1E5k5qS8=,iv:kEx1gOYT31eIRkW26SGO2nmQPzcZsYHKh4yEVtbu1gA=,tag:k1OGYOeBl6z02Zq6a5Kumw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
