---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: node-feature-discovery
      version: 2.1.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    crds: CreateReplace

  upgrade:
    crds: CreateReplace

  values:
    nodeFeatureRule:
      createCRD: true

      config:
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device

        custom:
        - name: "intel-gpu"
          matchOn:
            - pciId:
                class: ["0300"]
                vendor: ["8086"]
        - name: "ups-apc"
          matchOn:
            - usbId:
                vendor: ["051d",]
                device: ["0002"]

        - name: "zwave"
          matchOn:
            - usbId:
                vendor: ["0658"]
                device: ["0200"]
        - name: "ender3"
          matchOn:
            - usbId:
                vendor: ["1eaf"]
                device: ["0004"]

    podAnnotations:
      configmap.reloader.stakater.com/reload: "node-feature-discovery"

    master:
      replicaCount: 1
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
