---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-tools
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: v0.0.126
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    fullnameOverride: reloader

    tolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"

    resources:
      requests:
        cpu: 15m
        memory: 94M
      limits:
        cpu: 15m
        memory: 94M