---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kopia-maintenance
  namespace: storage
spec:
  schedule: "0 6 */3 * *"
  suspend: false
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 259200
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-repo
              image: ghcr.io/onedr0p/kopia:0.12.1@sha256:dfe496c5ab894bb5d6084150e7fc0a31c9d4d6472c2c9ea1e2e14ffee60d6d93
              command:
                - /bin/bash
                - -c
                - |-
                  until [ -f /snapshots/kopia.repository.f ]; do
                      printf "\e[1;32m%-6s\e[m\n" "Awaiting for the Kopia repo to become ready ..."
                      sleep 1
                  done
              volumeMounts:
                - name: snapshots
                  mountPath: /snapshots
          containers:
            - name: maintenance
              image: ghcr.io/onedr0p/kopia:0.12.1@sha256:dfe496c5ab894bb5d6084150e7fc0a31c9d4d6472c2c9ea1e2e14ffee60d6d93
              env:
                - name: TZ
                  value: "${TZ}"
                - name: KOPIA_CACHE_DIRECTORY
                  value: /snapshots/cache
                - name: KOPIA_LOG_DIR
                  value: /snapshots/logs
                - name: KOPIA_PASSWORD
                  value: "none"
              command:
                - /bin/bash
                - -c
                - |
                  printf "\e[1;32m%-6s\e[m\n" "[01/04] Connect to repo ..."       && kopia repo connect filesystem --path=/snapshots --override-hostname=cluster --override-username=root
                  printf "\e[1;32m%-6s\e[m\n" "[02/04] Set maintenance owner ..." && kopia maintenance set --owner=root@cluster
                  printf "\e[1;32m%-6s\e[m\n" "[03/04] Run maintenance ..."       && kopia maintenance run --full
                  printf "\e[1;32m%-6s\e[m\n" "[04/04] Disconnect from repo ..."  && kopia repo disconnect
              volumeMounts:
                - name: snapshots
                  mountPath: /snapshots
              securityContext:
                privileged: true
          volumes:
            - name: snapshots
              nfs:
                server: "${NFS_SERVER}"
                path: /mnt/user/k3s-backup/snapshots