---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recipes
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: rook-ceph
      namespace: rook-ceph

  values:
    image:
      repository: vabene1111/recipes
      tag: 1.4.5
      pullPolicy: IfNotPresent

    env:
      TIMEZONE: "${TZ}"
      SECRET_KEY: ${SECRET_RECIPES_SECRET_KEY}
      DEBUG: "0"
      ALLOWED_HOSTS: "*"
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: "${SECRET_RECIPES_POSTGRES_HOST}"
      POSTGRES_PORT: 5432
      POSTGRES_DB: recipes
      POSTGRES_USER: "${SECRET_RECIPES_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${SECRET_RECIPES_POSTGRES_PASSWORD}"
      GUNICORN_MEDIA: "0"
      FRACTION_PREF_DEFAULT: "0"
      COMMENT_PREF_DEFAULT: "1"
      SHOPPING_MIN_AUTOSYNC_INTERVAL: "5"

    sidecar:
      image:
        repository: nginx
        tag: 1.23.3
        pullPolicy: IfNotPresent

    persistence:
      media:
        enabled: true
        existingClaim: recipes-media-v1
        mountPath: /opt/recipes/mediafiles
      static:
        enabled: true
        type: emptyDir

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "food"

        hosts:
          - host: &host "recipes.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 11m
        memory: 381M
      limits:
        cpu: 11m
        memory: 381M
