---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recipes
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: recipes
      version: 6.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: traefik
      namespace: network
    - name: rook-ceph
      namespace: rook-ceph

  values:
    image:
      repository: vabene1111/recipes
      tag: 1.2.7
      pullPolicy: IfNotPresent

    env:
      SECRET_KEY: ${SECRET_RECIPES_SECRET_KEY}
      DEBUG: "0"
      ALLOWED_HOSTS: "*"
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: "${SECRET_RECIPES_POSTGRES_HOST}"
      POSTGRES_PORT: 5432
      POSTGRES_DB: recipes
      POSTGRES_USER: "${SECRET_RECIPES_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${SECRET_RECIPES_POSTGRES_PASSWORD}"
      GUNICORN_MEDIA: "0"
      TIMEZONE: Europe/Berlin
      FRACTION_PREF_DEFAULT: "0"
      COMMENT_PREF_DEFAULT: "1"
      SHOPPING_MIN_AUTOSYNC_INTERVAL: "5"

    sidecar:
      image:
        repository: nginx
        tag: 1.22.0
        pullPolicy: IfNotPresent

    persistence:
      media:
        enabled: true
        existingClaim: recipes-media-v1
        mountPath: /opt/recipes/mediafiles
      static:
        enabled: true
        type: emptyDir

    service:
      main:
        annotations:
          prometheus.io/probe: "true"
          prometheus.io/protocol: http

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "food"

        hosts:
          - host: "recipes.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: recipes-cert
            hosts:
              - "recipes.${SECRET_DOMAIN}"
