---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
