---
- name: Ensure volumes directory exists
  file:
    path: /nas02/shares
    state: directory
    mode: 0777

- name: Ensure dms-import inside volumes directory exists
  file:
    path: /nas02/shares/dms-import
    state: directory
    mode: 0777

- name: Ensure dms-import inside volumes directory exists
  file:
    path: /nas02/shares/dms-export
    state: directory
    mode: 0777

- name: Ensure dms-import inside volumes directory exists
  file:
    path: /nas02/shares/nzb-import
    state: directory
    mode: 0777

- name: Ensure required entries are made to hosts file. # Notes 1232
  lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item }}"
  with_items:
    - '/nas02/shares/dms-import  *(rw,no_root_squash,no_subtree_check,insecure)'
    - '/nas02/shares/dms-export *(rw,no_root_squash,no_subtree_check,insecure)'
    - '/nas02/shares/nzb-import *(rw,no_root_squash,no_subtree_check,insecure)'

- name: Restart nfs-kernel-server.service
  ansible.builtin.systemd:
    daemon_reload: yes
    state: started
    name: nfs-kernel-server.service

- name: Re-export the share
  command: exportfs -rav
