---
- name: Ensure Dateien share directory exists
  file:
    path: /nas02/shares/Dateien
    state: directory
    mode: 0777

- name: Create smb.conf file
  ansible.builtin.template:
    src: smb.conf.j2
    dest: "/etc/samba/smb.conf"
    mode: 0644

- name: Create smb.service file for Avahi
  ansible.builtin.template:
    src: smb.service.j2
    dest: "/etc/avahi/services/smb.service"
    mode: 0644

- name: Restart smbd.service
  ansible.builtin.systemd:
    state: restarted
    name: smbd.service

- name: Restart avahi-daemon.service
  ansible.builtin.systemd:
    state: restarted
    name: avahi-daemon.service
